### ISSUE TITLE
Problem with simple_switch_13.py

### ISSUE THREAD

**Issue by Nishan8583** [Broadcom-Switch/of-dpa#50]
**EVERY TIME I TRY TO RUN simple_switch_13.py I GET THE FOLLOWING ERROR**

unsupported version 0x1. If possible, set the switch to use one of the versions [4]
Error in the datapath None from ('192.168.85.145', 51710)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ryu/controller/controller.py", line 460, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.4/dist-packages/ryu/controller/controller.py", line 378, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.4/dist-packages/ryu/controller/controller.py", line 132, in deactivate
    method(self)
  File "/usr/local/lib/python3.4/dist-packages/ryu/controller/controller.py", line 281, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.4/dist-packages/ryu/controller/ofp_handler.py", line 180, in hello_handler
    self._hello_failed(datapath, error_desc)
  File "/usr/local/lib/python3.4/dist-packages/ryu/controller/ofp_handler.py", line 66, in _hello_failed
    datapath.send_msg(error_msg)
  File "/usr/local/lib/python3.4/dist-packages/ryu/controller/controller.py", line 347, in send_msg
    msg.serialize()
  File "/usr/local/lib/python3.4/dist-packages/ryu/ofproto/ofproto_parser.py", line 272, in serialize
    self._serialize_body()
  File "/usr/local/lib/python3.4/dist-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 253, in _serialize_body
    self.buf += self.data
TypeError: can't concat str to bytearray

**CAN SOMEONE HELP ME WITH THIS PROBLEM ?**

**Comment by davidgengenbach** [comment]
of-dpa is compatible with OpenFlow version 1.3, not 1.0.

```
from ryu.ofproto import ofproto_v1_0
# ...
OFP_VERSIONS = [ofproto_v1_0.OFP_VERSION]
```
should be
```
from ryu.ofproto import ofproto_v1_3

# ...

OFP_VERSIONS = [ofproto_v1_3.OFP_VERSION]
```

But I suspect that the code will not work after this change, too.
The default Ryu example code, even the Ryu controller code in this repo, does not work out of the box.
